name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Check Gradle version
        run: ./gradlew --version

      - name: List build/libs
        run: ls build/libs

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Deploying to server..."
          echo "SERVER_IP: $SERVER_IP"
          echo "SERVER_USER: $SERVER_USER"
          
          # Создание директории и очистка
          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "mkdir -p ~/myapp && rm -rf ~/myapp/*" || echo "Failed to create or clear directory on server"

          # Копирование файлов
          sshpass -p "$SERVER_PASSWORD" scp -r build/libs/* "$SERVER_USER@$SERVER_IP:~/myapp/" || echo "Failed to copy files to server"

          # Проверка наличия файла
          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "ls ~/myapp || echo 'Failed to list files in ~/myapp'" 

          # Запуск приложения
          sshpass -p "$SERVER_PASSWORD" ssh "$SERVER_USER@$SERVER_IP" "cd ~/myapp && java -jar macros_system.jar || echo 'Failed to run the jar file'"